import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}>

        <header className="w-full bg-red-500 text-center p-2">
          header
        </header>

        <main className="flex-1 flex justify-center items-center">
          {children}
        </main>

        <footer className="w-full bg-blue-500 text-center p-2">
          footer &reg;
        </footer>

      </body>
    </html>
  );
}

